development:
  adapter: sqlite3
  database: db/development.sqlite3
  pool: 5
  timeout: 15000

test:
  adapter: sqlite3
  database: db/test.sqlite3
  pool: 5
  timeout: 15000

production:
  adapter: mysql2
  encoding: utf8
  reconnect: false
  pool: 10
  host: mysql.csh.rit.edu
  database: webnews
  username: webnews
  password: <%= IO.read('/var/www/priv/webnews/db-key') rescue '' %>
